version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'crate-ci/typos'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
