name: CI - Go

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-go.yml'
      - '**.go'
      - 'go.*'
      - 'testdata/**'
  pull_request:
    paths:
      - '.github/workflows/ci-go.yml'
      - '**.go'
      - 'go.*'
      - 'testdata/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go test
      - run: go build -v -race
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: check format
        run: go fmt && git add --intent-to-add . && git diff --exit-code
      - run: go vet
      # Because of default in vscode extension
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          # Keep after `setup-go`, to use same go version
          install-go: false
          # Keep same version as used in *.nix
          version: '2023.1.6'
